package fuzzing

import (
	"fmt"
	"math/big"
	"reflect"
	"regexp"
	"strings"

	"github.com/crytic/medusa-geth/accounts/abi"
	"github.com/crytic/medusa/fuzzing/calls"
	"github.com/crytic/medusa/fuzzing/contracts"
	"github.com/crytic/medusa/fuzzing/valuegeneration"
	"github.com/crytic/medusa/utils"
	"github.com/crytic/medusa/utils/randomutils"
)

// CallSequenceGenerator generates call sequences iteratively per element, for use in fuzzing campaigns. It is attached
// to a FuzzerWorker and uses its runtime context
type CallSequenceGenerator struct {
	// worker describes the parent FuzzerWorker using this mutator. Calls will be generated against deployed contract
	// methods known to the worker.
	worker *FuzzerWorker

	// config describes the weights to use for each weighted random CallSequenceGeneratorMutationStrategy this
	// CallSequenceGenerator will use when generating new call sequences.
	config *CallSequenceGeneratorConfig

	// baseSequence describes the internal call sequence generated by InitializeNextSequence to use as a base when providing
	// potentially further mutated values with PopSequenceElement iteratively.
	baseSequence calls.CallSequence

	// fetchIndex describes the current position in the baseSequence which defines the next element to be mutated and
	// returned when calling PopSequenceElement.
	fetchIndex int

	// generateFromTail describes whether the CallSequenceGenerator generates a new call sequence from the tail
	// of the corpus.
	generateFromTail bool

	// keep the array of array lengths that is already generated
	generatedArrayLengths []int

	// prefetchModifyCallFunc describes the method to use to mutate the next indexed call sequence element, prior
	// to its fetching by PopSequenceElement.
	prefetchModifyCallFunc PrefetchModifyCallFunc

	// mutationStrategyChooser is a weighted random selector of functions that prepare the CallSequenceGenerator with
	// a baseSequence derived from corpus entries.
	mutationStrategyChooser *randomutils.WeightedRandomChooser[CallSequenceGeneratorMutationStrategy]
}

// CallSequenceGeneratorConfig defines the configuration for a CallSequenceGenerator to be created and used by a
// FuzzerWorker to generate call sequences in a fuzzing campaign.
type CallSequenceGeneratorConfig struct {
	// NewSequenceProbability defines the probability that the CallSequenceGenerator should generate an entirely new
	// sequence rather than mutating one from the corpus.
	NewSequenceProbability float32

	// RandomUnmodifiedCorpusHeadWeight defines the weight that the CallSequenceGenerator should use the call sequence
	// generation strategy of taking the head of a corpus sequence (without mutations) and append newly generated calls
	// to the end of it.
	RandomUnmodifiedCorpusHeadWeight uint64

	// RandomUnmodifiedCorpusTailWeight defines the weight that the CallSequenceGenerator should use the call sequence
	// generation strategy of taking the tail of a corpus sequence (without mutations) and prepend newly generated calls
	// to the start of it.
	RandomUnmodifiedCorpusTailWeight uint64

	// RandomUnmodifiedSpliceAtRandomWeight defines the weight that the CallSequenceGenerator should use the call sequence
	// generation strategy of taking two corpus sequences (without mutations) and splicing them before joining them
	// together.
	RandomUnmodifiedSpliceAtRandomWeight uint64

	// RandomUnmodifiedInterleaveAtRandomWeight defines the weight that the CallSequenceGenerator should use the call
	// sequence generation strategy of taking two corpus sequences (without mutations) and interleaving a random
	// number of calls from each.
	RandomUnmodifiedInterleaveAtRandomWeight uint64

	// RandomMutatedCorpusHeadWeight defines the weight that the CallSequenceGenerator should use the call sequence
	// generation strategy of taking the head of a corpus sequence (with mutations) and append newly generated calls
	// to the end of it.
	RandomMutatedCorpusHeadWeight uint64

	// RandomMutatedCorpusTailWeight defines the weight that the CallSequenceGenerator should use the call sequence
	// generation strategy of taking the tao; of a corpus sequence (with mutations) and prepend newly generated calls
	// to the start of it.
	RandomMutatedCorpusTailWeight uint64

	// RandomMutatedSpliceAtRandomWeight defines the weight that the CallSequenceGenerator should use the call sequence
	// generation strategy of taking two corpus sequences (with mutations) and splicing them before joining them
	// together.
	RandomMutatedSpliceAtRandomWeight uint64

	// RandomMutatedInterleaveAtRandomWeight defines the weight that the CallSequenceGenerator should use the call
	// sequence generation strategy of taking two corpus sequences (with mutations) and interleaving a random
	// number of calls from each.
	RandomMutatedInterleaveAtRandomWeight uint64

	// FunctionRelationBias defines the weight that the CallSequenceGenerator should use the call sequence
	// generation strategy of taking a function relation and mutating the call sequence based on it.
	FunctionRelationBias float32

	// ValueGenerator defines the value provider to use when generating new values for call sequences. This is used both
	// for ABI call data generation, and generation of additional values such as the "value" field of a
	// transaction/call.
	ValueGenerator valuegeneration.ValueGenerator

	// ValueMutator defines the value provider to use when mutating corpus call sequences.
	ValueMutator valuegeneration.ValueMutator
}

// CallSequenceGeneratorFunc defines a method used to populate a provided call sequence with generated calls.
// Returns an optional PrefetchModifyCallFunc to be executed prior to the fetching of each element, or an error if
// one occurs.
type CallSequenceGeneratorFunc func(sequenceGenerator *CallSequenceGenerator, sequence calls.CallSequence) error

// PrefetchModifyCallFunc defines a method used to modify a call sequence element before being fetched from this
// provider for use.
// Returns an error if one occurs.
type PrefetchModifyCallFunc func(sequenceGenerator *CallSequenceGenerator, element *calls.CallSequenceElement) error

// CallSequenceGeneratorMutationStrategy defines a structure for a mutation strategy used by a CallSequenceGenerator.
type CallSequenceGeneratorMutationStrategy struct {
	// CallSequenceGeneratorFunc describes a method used to populate a provided call sequence.
	CallSequenceGeneratorFunc CallSequenceGeneratorFunc

	// PrefetchModifyCallFunc defines a method used to modify a call sequence element before being fetched.
	PrefetchModifyCallFunc PrefetchModifyCallFunc
}

// NewCallSequenceGenerator creates a CallSequenceGenerator to generate call sequences for use in fuzzing campaigns.
func NewCallSequenceGenerator(worker *FuzzerWorker, config *CallSequenceGeneratorConfig) *CallSequenceGenerator {
	generator := &CallSequenceGenerator{
		worker:                  worker,
		config:                  config,
		mutationStrategyChooser: randomutils.NewWeightedRandomChooser[CallSequenceGeneratorMutationStrategy](),
	}

	generator.mutationStrategyChooser.AddChoices(
		randomutils.NewWeightedRandomChoice(
			CallSequenceGeneratorMutationStrategy{
				CallSequenceGeneratorFunc: callSeqGenFuncCorpusHead,
				PrefetchModifyCallFunc:    nil,
			},
			new(big.Int).SetUint64(config.RandomUnmodifiedCorpusHeadWeight),
		),
		randomutils.NewWeightedRandomChoice(
			CallSequenceGeneratorMutationStrategy{
				CallSequenceGeneratorFunc: callSeqGenFuncCorpusTail,
				PrefetchModifyCallFunc:    nil,
			},
			new(big.Int).SetUint64(config.RandomUnmodifiedCorpusTailWeight),
		),
		randomutils.NewWeightedRandomChoice(
			CallSequenceGeneratorMutationStrategy{
				CallSequenceGeneratorFunc: callSeqGenFuncSpliceAtRandom,
				PrefetchModifyCallFunc:    nil,
			},
			new(big.Int).SetUint64(config.RandomUnmodifiedSpliceAtRandomWeight),
		),
		randomutils.NewWeightedRandomChoice(
			CallSequenceGeneratorMutationStrategy{
				CallSequenceGeneratorFunc: callSeqGenFuncInterleaveAtRandom,
				PrefetchModifyCallFunc:    nil,
			},
			new(big.Int).SetUint64(config.RandomUnmodifiedInterleaveAtRandomWeight),
		),
		randomutils.NewWeightedRandomChoice(
			CallSequenceGeneratorMutationStrategy{
				CallSequenceGeneratorFunc: callSeqGenFuncCorpusHead,
				PrefetchModifyCallFunc:    prefetchModifyCallFuncMutate,
			},
			new(big.Int).SetUint64(config.RandomMutatedCorpusHeadWeight),
		),
		randomutils.NewWeightedRandomChoice(
			CallSequenceGeneratorMutationStrategy{
				CallSequenceGeneratorFunc: callSeqGenFuncCorpusTail,
				PrefetchModifyCallFunc:    prefetchModifyCallFuncMutate,
			},
			new(big.Int).SetUint64(config.RandomMutatedCorpusTailWeight),
		),
		randomutils.NewWeightedRandomChoice(
			CallSequenceGeneratorMutationStrategy{
				CallSequenceGeneratorFunc: callSeqGenFuncSpliceAtRandom,
				PrefetchModifyCallFunc:    prefetchModifyCallFuncMutate,
			},
			new(big.Int).SetUint64(config.RandomMutatedSpliceAtRandomWeight),
		),
		randomutils.NewWeightedRandomChoice(
			CallSequenceGeneratorMutationStrategy{
				CallSequenceGeneratorFunc: callSeqGenFuncInterleaveAtRandom,
				PrefetchModifyCallFunc:    prefetchModifyCallFuncMutate,
			},
			new(big.Int).SetUint64(config.RandomMutatedInterleaveAtRandomWeight),
		),
	)

	return generator
}

// InitializeNextSequence prepares the CallSequenceGenerator for generating a new sequence. Each element can be
// obtained by calling PopSequenceElement iteratively.
// Returns a boolean indicating whether the initialized sequence is a newly generated sequence (rather than an
// unmodified one loaded from the corpus), or an error if one occurred.
func (g *CallSequenceGenerator) InitializeNextSequence(fuzzing_loop_counter int) (bool, error) {
	// fmt.Println("\n\nCuEVM Debug: InitializeNextSequence\n\n")
	g.generateFromTail = false
	// Reset the state of our generator.
	g.baseSequence = make(calls.CallSequence, g.worker.fuzzer.config.Fuzzing.CallSequenceLength)
	g.fetchIndex = 0
	g.prefetchModifyCallFunc = nil

	// Check if there are any previously un-executed corpus call sequences. If there are, the fuzzer should execute
	// those first.
	unexecutedSequence := g.worker.fuzzer.corpus.UnexecutedCallSequence()
	if unexecutedSequence != nil {
		fmt.Println("CuEVM Debug: unexecutedSequence", unexecutedSequence)
		g.baseSequence = *unexecutedSequence
		return false, nil
	}

	// We'll decide whether to create a new call sequence or mutating existing corpus call sequences. Any entries we
	// leave as nil will be populated by a newly generated call prior to being fetched from this provider.

	// If this provider has no corpus mutation methods or corpus call sequences, we return a call sequence with
	// nil elements to signal that we want an entirely new sequence.
	if g.mutationStrategyChooser.ChoiceCount() == 0 || g.worker.fuzzer.corpus.ActiveMutableSequenceCount() == 0 || fuzzing_loop_counter == 0 {
		// fmt.Println("CuEVM Debug: no corpus mutation methods or corpus call sequences")
		return true, nil
	}

	// Determine whether we will generate a corpus based mutated sequence.
	if g.worker.randomProvider.Float32() > g.config.NewSequenceProbability {
		// fmt.Println("CuEVM Debug: generate a corpus based mutated sequence")
		// Get a random mutator function.
		corpusMutationFunc, err := g.mutationStrategyChooser.Choose()
		if err != nil {
			return true, fmt.Errorf("could not generate a corpus mutation derived call sequence due to an error obtaining a mutation method: %v", err)
		}

		// If we have a corpus mutation method, call it to generate our base sequence, then set the pre-fetch modify
		// call function.
		if corpusMutationFunc != nil && corpusMutationFunc.CallSequenceGeneratorFunc != nil {
			err = corpusMutationFunc.CallSequenceGeneratorFunc(g, g.baseSequence)
			if err != nil {
				return true, fmt.Errorf("could not generate a corpus mutation derived call sequence due to an error executing a mutation method: %v", err)
			}
			g.prefetchModifyCallFunc = corpusMutationFunc.PrefetchModifyCallFunc
		} else {
			g.generateFromTail = false
		}
	}

	return true, nil
}

// hasDynamicEncoding detects if a function signature contains dynamic types (bytes, string, or dynamic arrays)
func hasDynamicEncoding(signature string) bool {
	// Extract parameters between parentheses
	start := strings.Index(signature, "(")
	end := strings.LastIndex(signature, ")")
	if start == -1 || end == -1 || start >= end {
		return false
	}
	params := signature[start+1 : end]

	// Check for dynamic patterns
	return strings.Contains(params, "[]") || // dynamic arrays
		strings.Contains(params, "string") || // string type
		(strings.Contains(params, "bytes") && !regexp.MustCompile(`bytes\d`).MatchString(params)) // dynamic bytes (not bytes1, bytes2, etc.)
}

// Warning: this function is not thread safe, and should only be called once at the beginning of the fuzzing campaign
func (g *CallSequenceGenerator) seedSequenceElementCache() {
	// fmt.Println("\n\nCuEVM Debug: seedSequenceElementCache")
	selectedSender := g.worker.fuzzer.senders[g.worker.randomProvider.Intn(len(g.worker.fuzzer.senders))]
	big_one := big.NewInt(1)
	big_zero := big.NewInt(0)
	g.worker.fuzzer.normalizedSigCache = make(map[string]string)
	markerOffset := 0
	for _, method := range g.worker.stateChangingMethods {
		// fmt.Println("CuEVM Debug: method signature", method.Method.Sig)
		// fmt.Println("CuEVM Debug: method", method.Method)
		normalizedSig := normalizeSignature(method.Method.Sig)
		g.worker.fuzzer.normalizedSigCache[normalizedSig] = method.Method.Sig
		isDynamic := hasDynamicEncoding(method.Method.Sig)
		if isDynamic {
			g.worker.fuzzer.signatureDynamicEncoding = append(g.worker.fuzzer.signatureDynamicEncoding, method.Method.Sig)
			continue
		}
		args := make([]any, len(method.Method.Inputs))
		g.generatedArrayLengths = make([]int, 0)
		for i := 0; i < len(args); i++ {
			// Create our fuzzed parameters.
			input := method.Method.Inputs[i]
			// args[i] = valuegeneration.GenerateAbiValue(g.config.ValueGenerator, &input.Type)
			if len(g.generatedArrayLengths) == 0 {
				args[i] = valuegeneration.GenerateAbiValueWithArrayLength(g.config.ValueGenerator, &input.Type, -1)
			} else {
				// 50% chance to use the existing array length
				if g.worker.randomProvider.Intn(2) == 0 {
					args[i] = valuegeneration.GenerateAbiValueWithArrayLength(g.config.ValueGenerator, &input.Type, -1)
				} else {
					random_idx := g.worker.randomProvider.Intn(len(g.generatedArrayLengths))
					args[i] = valuegeneration.GenerateAbiValueWithArrayLength(g.config.ValueGenerator, &input.Type, g.generatedArrayLengths[random_idx])
				}
			}
			// fmt.Println("CuEVM Debug: args[i]", args[i])
			// fmt.Println("CuEVM Debug: input.Type", input.Type)
			if input.Type.T == abi.SliceTy {
				reflectValue := reflect.ValueOf(args[i])
				actualLength := reflectValue.Len() // This will give you the length
				g.generatedArrayLengths = append(g.generatedArrayLengths, actualLength)
				// fmt.Println("CuEVM Debug: generatedArrayLengths", g.generatedArrayLengths)
			}
		}
		msg, markers := calls.NewCallMessageWithAbiValueDataAndMask(selectedSender, &method.Address, 0, big_zero, g.worker.fuzzer.config.Fuzzing.TransactionGasLimit, big_one, big_zero, big_zero, &calls.CallMessageDataAbiValues{
			Method:      &method.Method,
			InputValues: args,
		})
		// clone call data
		clonedData := make([]byte, len(msg.Data))
		copy(clonedData, msg.Data)
		g.worker.fuzzer.staticABICallData = append(g.worker.fuzzer.staticABICallData, clonedData)
		g.worker.fuzzer.staticABIDataABIValues = append(g.worker.fuzzer.staticABIDataABIValues, *msg.DataAbiValues)
		g.worker.fuzzer.staticABISignature = append(g.worker.fuzzer.staticABISignature, method.Method.Sig)
		g.worker.fuzzer.staticABIMarkers = append(g.worker.fuzzer.staticABIMarkers, markers)
		g.worker.fuzzer.staticABIMarkerOffset = append(g.worker.fuzzer.staticABIMarkerOffset, uint32(markerOffset))
		g.worker.fuzzer.staticABIFlattenedMarkers = append(g.worker.fuzzer.staticABIFlattenedMarkers, uint32(len(markers)))
		markerOffset += 1

		if len(markers) > 0 {
			for _, marker := range markers {
				g.worker.fuzzer.staticABIFlattenedMarkers = append(g.worker.fuzzer.staticABIFlattenedMarkers, uint32(marker.Offset), uint32(marker.Type), uint32(marker.Length))
			}

			markerOffset += len(markers) * 3
		}
		g.worker.fuzzer.staticABIMarkerIndexMap[method.Method.Sig] = len(g.worker.fuzzer.staticABISignature) - 1
	}

	for _, method := range g.worker.pureMethods {
		// fmt.Println("CuEVM Debug: pure method", method.Method.Name, "payable", method.Method.Payable, "rawName", method.Method.RawName, "sig", method.Method.Sig)
		// fmt.Println("CuEVM Debug: pure method signature", method.Method.Sig, method.Method.Sig == "")
		normalizedSig := normalizeSignature(method.Method.Sig)
		g.worker.fuzzer.normalizedSigCache[normalizedSig] = method.Method.Sig
		isDynamic := hasDynamicEncoding(method.Method.Sig)
		if isDynamic {
			g.worker.fuzzer.signatureDynamicEncoding = append(g.worker.fuzzer.signatureDynamicEncoding, method.Method.Sig)
			continue
		}
		args := make([]any, len(method.Method.Inputs))
		g.generatedArrayLengths = make([]int, 0)
		for i := 0; i < len(args); i++ {
			// Create our fuzzed parameters.
			input := method.Method.Inputs[i]
			// args[i] = valuegeneration.GenerateAbiValue(g.config.ValueGenerator, &input.Type)
			if len(g.generatedArrayLengths) == 0 {
				args[i] = valuegeneration.GenerateAbiValueWithArrayLength(g.config.ValueGenerator, &input.Type, -1)
			} else {
				// 50% chance to use the existing array length
				if g.worker.randomProvider.Intn(2) == 0 {
					args[i] = valuegeneration.GenerateAbiValueWithArrayLength(g.config.ValueGenerator, &input.Type, -1)
				} else {
					random_idx := g.worker.randomProvider.Intn(len(g.generatedArrayLengths))
					args[i] = valuegeneration.GenerateAbiValueWithArrayLength(g.config.ValueGenerator, &input.Type, g.generatedArrayLengths[random_idx])
				}
			}
			// fmt.Println("CuEVM Debug: args[i]", args[i])
			// fmt.Println("CuEVM Debug: input.Type", input.Type)
			if input.Type.T == abi.SliceTy {
				reflectValue := reflect.ValueOf(args[i])
				actualLength := reflectValue.Len() // This will give you the length
				g.generatedArrayLengths = append(g.generatedArrayLengths, actualLength)
				// fmt.Println("CuEVM Debug: generatedArrayLengths", g.generatedArrayLengths)
			}
		}

		msg, markers := calls.NewCallMessageWithAbiValueDataAndMask(selectedSender, &method.Address, 0, big_zero, g.worker.fuzzer.config.Fuzzing.TransactionGasLimit, big_one, big_zero, big_zero, &calls.CallMessageDataAbiValues{
			Method:      &method.Method,
			InputValues: args,
		})
		// clone call data
		clonedData := make([]byte, len(msg.Data))
		copy(clonedData, msg.Data)
		g.worker.fuzzer.staticABICallData = append(g.worker.fuzzer.staticABICallData, clonedData)
		g.worker.fuzzer.staticABIDataABIValues = append(g.worker.fuzzer.staticABIDataABIValues, *msg.DataAbiValues)
		g.worker.fuzzer.staticABISignature = append(g.worker.fuzzer.staticABISignature, method.Method.Sig)
		g.worker.fuzzer.staticABIMarkers = append(g.worker.fuzzer.staticABIMarkers, markers)
		g.worker.fuzzer.staticABIMarkerOffset = append(g.worker.fuzzer.staticABIMarkerOffset, uint32(markerOffset))
		g.worker.fuzzer.staticABIFlattenedMarkers = append(g.worker.fuzzer.staticABIFlattenedMarkers, uint32(len(markers)))
		markerOffset += 1

		if len(markers) > 0 {
			for _, marker := range markers {
				g.worker.fuzzer.staticABIFlattenedMarkers = append(g.worker.fuzzer.staticABIFlattenedMarkers, uint32(marker.Offset), uint32(marker.Type), uint32(marker.Length))
			}

			markerOffset += len(markers) * 3
		}

		g.worker.fuzzer.staticABIMarkerIndexMap[method.Method.Sig] = len(g.worker.fuzzer.staticABISignature) - 1
	}

	normalizedSigCache := g.worker.fuzzer.normalizedSigCache
	// add fallback
	normalizedSigCache["()"] = "CuEVM::fallback()"
	normalizedSigCache["fallback()"] = "CuEVM::fallback()"
	normalizedSigCache["receive()"] = "CuEVM::fallback()"

	g.worker.fuzzer.functionImpactsCache = make(map[string][]string)
	g.worker.fuzzer.functionIsImpactedCache = make(map[string][]string)
	g.worker.fuzzer.functionsWithImpactsCache = make([]string, 0)

	allContractNames := make([]string, 0)
	functionIsConstructor := func(functionName string) bool {
		for _, contractName := range allContractNames {
			if strings.HasPrefix(functionName, contractName+"(") {
				return true
			}
		}
		if strings.HasPrefix(functionName, "constructor(") {
			return true
		}
		return false
	}
	if g.worker.fuzzer.slitherResults != nil {
		// Collect all contract names
		for contractName := range g.worker.fuzzer.slitherResults.FunctionRelations {
			allContractNames = append(allContractNames, contractName)
		}

		// Helper function to check if a function should be skipped
		shouldSkipFunction := func(funcName string) bool {
			return functionIsConstructor(funcName) || normalizedSigCache[funcName] == ""
		}

		// Helper function to add unique elements to a slice
		addUniqueToSlice := func(slice []string, item string) []string {
			for _, existing := range slice {
				if existing == item {
					return slice
				}
			}
			return append(slice, item)
		}

		// Track functions that have impacts to avoid duplicates
		functionsWithImpactsSet := make(map[string]bool)

		fmt.Println("CuEVM Debug: Processing function relations...")
		for contractName, relations := range g.worker.fuzzer.slitherResults.FunctionRelations {
			fmt.Printf("CuEVM Debug: Processing contract %s\n", contractName)

			for _, rel := range relations {
				// Skip constructors and functions without normalized signatures
				if shouldSkipFunction(rel.Function) {
					continue
				}

				methodSig := g.worker.fuzzer.normalizedSigCache[rel.Function]

				// Process impacts - functions that this method affects
				if len(rel.Impacts) > 0 {
					for _, impact := range rel.Impacts {
						if shouldSkipFunction(impact) {
							continue
						}

						normalizedImpact := normalizedSigCache[impact]
						g.worker.fuzzer.functionImpactsCache[methodSig] = addUniqueToSlice(
							g.worker.fuzzer.functionImpactsCache[methodSig],
							normalizedImpact,
						)
					}

					// Track this function as having impacts (deduplicated)
					if !functionsWithImpactsSet[methodSig] {
						g.worker.fuzzer.functionsWithImpactsCache = append(g.worker.fuzzer.functionsWithImpactsCache, methodSig)
						functionsWithImpactsSet[methodSig] = true
					}
				}

				// Process isImpactedBy - functions that affect this method
				if len(rel.IsImpactedBy) > 0 {
					for _, impactedBy := range rel.IsImpactedBy {
						if shouldSkipFunction(impactedBy) {
							continue
						}

						normalizedImpactedBy := normalizedSigCache[impactedBy]
						g.worker.fuzzer.functionIsImpactedCache[methodSig] = addUniqueToSlice(
							g.worker.fuzzer.functionIsImpactedCache[methodSig],
							normalizedImpactedBy,
						)
					}
				}
			}
		}
	}
	// Print comprehensive cache debugging information
	fmt.Println("\n=== Cache Summary ===")
	fmt.Printf("Total normalized signatures cached: %d\n", len(g.worker.fuzzer.normalizedSigCache))
	fmt.Printf("Total function impacts cached: %d\n", len(g.worker.fuzzer.functionImpactsCache))
	fmt.Printf("Total function isImpactedBy cached: %d\n", len(g.worker.fuzzer.functionIsImpactedCache))
	fmt.Printf("Total functions with impacts: %d\n", len(g.worker.fuzzer.functionsWithImpactsCache))

	fmt.Println("\n=== Normalized Signature Cache ===")
	for original, normalized := range g.worker.fuzzer.normalizedSigCache {
		fmt.Printf("  %s -> %s\n", original, normalized)
	}

	fmt.Println("\n=== Functions With Impacts Cache ===")
	for i, method := range g.worker.fuzzer.functionsWithImpactsCache {
		fmt.Printf("  [%d] %s\n", i, method)
	}

	fmt.Println("\n=== Function Impacts Cache ===")
	for cacheKey, impacts := range g.worker.fuzzer.functionImpactsCache {
		fmt.Printf("  %s -> %v\n", cacheKey, impacts)
	}

	fmt.Println("\n=== Function IsImpactedBy Cache ===")
	for cacheKey, isImpactedBy := range g.worker.fuzzer.functionIsImpactedCache {
		fmt.Printf("  %s -> %v\n", cacheKey, isImpactedBy)
	}

	fmt.Println("\n=== Cache Validation ===")
	// Validate cache consistency
	totalCacheEntries := len(g.worker.fuzzer.functionImpactsCache) + len(g.worker.fuzzer.functionIsImpactedCache)
	fmt.Printf("Total cache entries: %d\n", totalCacheEntries)

	fmt.Println("\n\nCuEVM Debug: end seedSequenceElementCache\n\n")

}

// PopSequenceElement obtains the next element for our call sequence requested by InitializeNextSequence. If there are no elements
// left to return, this method returns nil. If an error occurs, it is returned instead.
func (g *CallSequenceGenerator) PopSequenceElement() (*calls.CallSequenceElement, error) {
	// If the call sequence length is zero, there is no work to be done.
	if g.fetchIndex >= len(g.baseSequence) {
		return nil, nil
	}

	// Obtain our base call element
	element := g.baseSequence[g.fetchIndex]

	// Debug printing
	// fmt.Printf("CuEVM Debug: PopSequenceElement - fetchIndex: %d, element is nil: %v\n", g.fetchIndex, element == nil)
	// If it is nil, we generate an entirely new call. Otherwise, we apply pre-execution modifications.
	if element == nil {
		// Pool of candidate (contract, function) pairs
		var pool []string

		if g.worker.randomProvider.Float32() < g.config.FunctionRelationBias && (g.fetchIndex != 0) {
			// fmt.Println("\nCuEVM Debug: use function relation")
			if g.generateFromTail {
				// fmt.Println("CuEVM Debug: generateFromTail")
				for _, elem := range g.baseSequence[g.fetchIndex:] {
					if elem == nil {
						continue
					}

					// fmt.Println("CuEVM Debug:", elem.Call.DataAbiValues.Method.Sig, "is impacted by", g.worker.fuzzer.functionIsImpactedCache[elem.Call.DataAbiValues.Method.Sig])
					pool = append(pool, g.worker.fuzzer.functionIsImpactedCache[elem.Call.DataAbiValues.Method.Sig]...)

				}
			} else {
				if g.fetchIndex != 0 {
					// check if we should use function relation

					// Build the pool from the current sequence
					for _, elem := range g.baseSequence[:g.fetchIndex] {
						if elem == nil {
							continue
						}

						// fmt.Println("CuEVM Debug:" ,elem.Call.DataAbiValues.Method.Sig, " impacts", g.worker.fuzzer.functionImpactsCache[elem.Call.DataAbiValues.Method.Sig])
						pool = append(pool, g.worker.fuzzer.functionImpactsCache[elem.Call.DataAbiValues.Method.Sig]...)

					}

				} else {
					// first element, we pick from the methods having Impacts
					pool = g.worker.fuzzer.functionsWithImpactsCache
				}
			}
		}
		// fmt.Println("CuEVM Debug: function relation pool", pool)

		elementWithMask, _, err := g.generateNewElementWithMutationMask(pool, g.fetchIndex)
		if err != nil {
			return nil, err
		}
		element = elementWithMask

		g.baseSequence[g.fetchIndex] = element
		// Debug print the masks

		// fmt.Printf("CuEVM Debug: Method: %s\n", elementWithMask)
		// fmt.Println("CuEVM Debug: masks", elementWithMask.Call.DataMarkers)

	} else {
		// We have an element, if our generator set a post-call modify for this function, execute it now to modify
		// our call prior to return. This allows mutations to be applied on a per-call time frame, rather than
		// per-sequence, making use of the most recent runtime data.
		// fmt.Println("CuEVM Debug: Element is not nil ", g.prefetchModifyCallFunc)
		// CuEVM: we don't need to modify the call, we will mutate on GPU side
	}

	// Update the element with the current nonce for the associated chain.
	// element.Call.FillFromTestChainProperties(g.worker.chain)

	// Update our base sequence, advance our position, and return the processed element from this round.

	// fmt.Println("CuEVM Debug: PopSequenceElement - element", element)
	g.fetchIndex++
	return element, nil
}

// generateNewElement generates a new call sequence element which targets a method in a contract
// deployed to the CallSequenceGenerator's parent FuzzerWorker chain, with fuzzed call data.
// Returns the call sequence element, or an error if one was encountered.
func (g *CallSequenceGenerator) generateNewElementWithChosenMethod(selectedMethod *contracts.DeployedContractMethod, forceValue bool) (*calls.CallSequenceElement, error) {
	// Seed a fixed sender
	selectedSender := g.worker.fuzzer.senders[0]
	// Generate fuzzed parameters for the function call
	args := make([]any, len(selectedMethod.Method.Inputs))
	for i := 0; i < len(args); i++ {
		// Create our fuzzed parameters.
		input := selectedMethod.Method.Inputs[i]
		args[i] = valuegeneration.GenerateAbiValue(g.config.ValueGenerator, &input.Type)
	}

	// If this is a payable function, generate value to send
	var value *big.Int
	value = big.NewInt(0)
	if selectedMethod.Method.StateMutability == "payable" || forceValue {
		value = big.NewInt(1234) // g.config.ValueGenerator.GenerateInteger(false, 64)
	}
	var zero *big.Int = big.NewInt(0)
	// Create our message using the provided parameters.
	// We fill out some fields and populate the rest from our TestChain properties.
	// TODO: We likely want to make gasPrice fluctuate within some sensible range here.
	msg := calls.NewCallMessageWithAbiValueData(selectedSender, &selectedMethod.Address, 0, value, g.worker.fuzzer.config.Fuzzing.TransactionGasLimit, zero, zero, zero, &calls.CallMessageDataAbiValues{
		Method:      &selectedMethod.Method,
		InputValues: args,
	})

	if g.worker.fuzzer.config.Fuzzing.TestChainConfig.SkipAccountChecks {
		msg.SkipAccountChecks = true
	}

	// Determine our delay values for this element
	blockNumberDelay := uint64(0)
	blockTimestampDelay := uint64(0)
	if g.worker.fuzzer.config.Fuzzing.MaxBlockNumberDelay > 0 {
		blockNumberDelay = g.config.ValueGenerator.GenerateInteger(false, 64).Uint64() % (g.worker.fuzzer.config.Fuzzing.MaxBlockNumberDelay + 1)
	}
	if g.worker.fuzzer.config.Fuzzing.MaxBlockTimestampDelay > 0 {
		blockTimestampDelay = g.config.ValueGenerator.GenerateInteger(false, 64).Uint64() % (g.worker.fuzzer.config.Fuzzing.MaxBlockTimestampDelay + 1)
	}

	// For each block we jump, we need a unique time stamp for chain semantics, so if our block number jump is too small,
	// while our timestamp jump is larger, we cap it.
	if blockNumberDelay > blockTimestampDelay {
		if blockTimestampDelay == 0 {
			blockNumberDelay = 0
		} else {
			blockNumberDelay %= blockTimestampDelay
		}
	}

	// Return our call sequence element.
	return calls.NewCallSequenceElement(selectedMethod.Contract, msg, blockNumberDelay, blockTimestampDelay), nil
}

// generateNewElement generates a new call sequence element which targets a method in a contract
// deployed to the CallSequenceGenerator's parent FuzzerWorker chain, with fuzzed call data.
// Returns the call sequence element, or an error if one was encountered.
func (g *CallSequenceGenerator) generateNewElement() (*calls.CallSequenceElement, error) {
	// Check to make sure that we have any functions to call
	if len(g.worker.stateChangingMethods) == 0 && len(g.worker.pureMethods) == 0 {
		return nil, fmt.Errorf("cannot generate fuzzed call as there are no methods to call")
	}

	// Only call view functions if there are no state-changing methods
	var callOnlyPureFunctions bool
	if len(g.worker.stateChangingMethods) == 0 && len(g.worker.pureMethods) > 0 {
		callOnlyPureFunctions = true
	}

	// Select a random method
	// There is a 1/1000 chance that a pure method will be invoked or if there are only pure functions that are callable
	var selectedMethod *contracts.DeployedContractMethod
	// CuEVM: many txs in paralel so we can afford to increase this chance
	if (len(g.worker.pureMethods) > 0 && g.worker.randomProvider.Intn(100) == 1) || callOnlyPureFunctions {
		fmt.Println("CuEVM Debug: generate a pure method")
		// if (len(g.worker.pureMethods) > 0 && g.worker.randomProvider.Intn(1000) == 0) || callOnlyPureFunctions {
		selectedMethod = &g.worker.pureMethods[g.worker.randomProvider.Intn(len(g.worker.pureMethods))]
	} else {
		fmt.Println("CuEVM Debug: generate a state changing method")
		selectedMethod = &g.worker.stateChangingMethods[g.worker.randomProvider.Intn(len(g.worker.stateChangingMethods))]
	}

	// Select a random sender
	selectedSender := g.worker.fuzzer.senders[g.worker.randomProvider.Intn(len(g.worker.fuzzer.senders))]

	// Generate fuzzed parameters for the function call
	args := make([]any, len(selectedMethod.Method.Inputs))
	for i := 0; i < len(args); i++ {
		// Create our fuzzed parameters.
		input := selectedMethod.Method.Inputs[i]
		args[i] = valuegeneration.GenerateAbiValue(g.config.ValueGenerator, &input.Type)
	}

	// If this is a payable function, generate value to send
	var value *big.Int
	value = big.NewInt(0)
	if selectedMethod.Method.StateMutability == "payable" {
		value = g.config.ValueGenerator.GenerateInteger(false, 64)
	}

	// Create our message using the provided parameters.
	// We fill out some fields and populate the rest from our TestChain properties.
	// TODO: We likely want to make gasPrice fluctuate within some sensible range here.
	msg := calls.NewCallMessageWithAbiValueData(selectedSender, &selectedMethod.Address, 0, value, g.worker.fuzzer.config.Fuzzing.TransactionGasLimit, nil, nil, nil, &calls.CallMessageDataAbiValues{
		Method:      &selectedMethod.Method,
		InputValues: args,
	})

	if g.worker.fuzzer.config.Fuzzing.TestChainConfig.SkipAccountChecks {
		msg.SkipAccountChecks = true
	}

	// Determine our delay values for this element
	blockNumberDelay := uint64(0)
	blockTimestampDelay := uint64(0)
	if g.worker.fuzzer.config.Fuzzing.MaxBlockNumberDelay > 0 {
		blockNumberDelay = g.config.ValueGenerator.GenerateInteger(false, 64).Uint64() % (g.worker.fuzzer.config.Fuzzing.MaxBlockNumberDelay + 1)
	}
	if g.worker.fuzzer.config.Fuzzing.MaxBlockTimestampDelay > 0 {
		blockTimestampDelay = g.config.ValueGenerator.GenerateInteger(false, 64).Uint64() % (g.worker.fuzzer.config.Fuzzing.MaxBlockTimestampDelay + 1)
	}

	// For each block we jump, we need a unique time stamp for chain semantics, so if our block number jump is too small,
	// while our timestamp jump is larger, we cap it.
	if blockNumberDelay > blockTimestampDelay {
		if blockTimestampDelay == 0 {
			blockNumberDelay = 0
		} else {
			blockNumberDelay %= blockTimestampDelay
		}
	}

	// Return our call sequence element.
	return calls.NewCallSequenceElement(selectedMethod.Contract, msg, blockNumberDelay, blockTimestampDelay), nil
}

// normalizeSignature replaces all array size specifiers with []
func normalizeSignature(sig string) string {
	re := regexp.MustCompile(`\[\d*\]`)
	return re.ReplaceAllString(sig, "[]")
}

// generateNewElementWithMutationMask generates a new call sequence element which targets a method in a contract
// deployed to the CallSequenceGenerator's parent FuzzerWorker chain, with fuzzed call data and mutation masks.
// Returns the call sequence element, mutation masks for each argument, or an error if one was encountered.
func (g *CallSequenceGenerator) generateNewElementWithMutationMask(candidate_pool []string, fetch_index int) (*calls.CallSequenceElement, []calls.DataMarker, error) {
	// Check to make sure that we have any functions to call
	if len(g.worker.stateChangingMethods) == 0 && len(g.worker.pureMethods) == 0 {
		return nil, nil, fmt.Errorf("cannot generate fuzzed call as there are no methods to call")
	}

	// Only call view functions if there are no state-changing methods
	var callOnlyPureFunctions bool
	if len(g.worker.stateChangingMethods) == 0 && len(g.worker.pureMethods) > 0 {
		callOnlyPureFunctions = true
	}
	// Select a random method
	// There is a 1/1000 chance that a pure method will be invoked or if there are only pure functions that are callable
	var selectedMethod *contracts.DeployedContractMethod
	if len(candidate_pool) > 0 {

		// select a random candidate from the pool
		selectedSig := candidate_pool[g.worker.randomProvider.Intn(len(candidate_pool))]
		selectedMethod = g.worker.signatureToMethodMap[selectedSig]
		// fmt.Println("CuEVM Debug: selectedMethod from pool", selectedMethod)
		// fmt.Println("CuEVM Debug: selectedMethod.Method.Sig from pool", selectedMethod.Method.Sig)
	} else {
		// CuEVM: many txs in paralel so we can afford to increase this chance
		if (len(g.worker.pureMethods) > 0 && g.worker.randomProvider.Intn(100) == 1) || callOnlyPureFunctions {
			// if (len(g.worker.pureMethods) > 0 && g.worker.randomProvider.Intn(1000) == 0) || callOnlyPureFunctions {
			selectedMethod = &g.worker.pureMethods[g.worker.randomProvider.Intn(len(g.worker.pureMethods))]
			// if selectedMethod.Method.Sig == "CuEVM::fallback()" && (g.worker.randomProvider.Intn(20) != 1) {
			// 	// lower chance to select fallback
			// 	selectedMethod = &g.worker.pureMethods[g.worker.randomProvider.Intn(len(g.worker.pureMethods))]
			// }
		} else {
			selectedMethod = &g.worker.stateChangingMethods[g.worker.randomProvider.Intn(len(g.worker.stateChangingMethods))]
		}

	}
	// CuEVM Debug
	// fmt.Println("CuEVM Debug: candidate_pool", candidate_pool)
	// fmt.Println("CuEVM Debug: selectedMethod", selectedMethod.Method.Sig)
	// fmt.Println("\n\nCuEVM Debug: selectedMethod.Method.Sig", selectedMethod.Method.Sig)
	// Select a random sender
	selectedSender := g.worker.fuzzer.senders[g.worker.randomProvider.Intn(len(g.worker.fuzzer.senders))]
	// If this is a payable function, generate value to send
	var value *big.Int
	value = big.NewInt(0)

	// it's directly mutated on GPU side
	// if selectedMethod.Method.StateMutability == "payable" {
	// 	randUint := g.worker.randomProvider.Uint64()
	// 	value.SetUint64(randUint)
	// }

	big_one := big.NewInt(1)
	big_zero := big.NewInt(0)
	var msg *calls.CallMessage
	var masks []calls.DataMarker

	cachedCallData, exists := g.worker.staticABICallElementCache[selectedMethod.Method.Sig]
	if exists {
		// fmt.Println("\n\nUsing cached static ABI call element", selectedMethod.Method.Sig)
		abiValues := g.worker.staticABIDataABIValues[selectedMethod.Method.Sig] // must exist
		msg = calls.NewCallMessageWithData(
			selectedSender,
			&selectedMethod.Address,
			0,
			value,
			g.worker.fuzzer.config.Fuzzing.TransactionGasLimit,
			big_one,
			big_zero,
			big_zero,
			cachedCallData,
			&abiValues,
		)
		masks = nil
		msg.DataMarkers = nil
	} else {
		// fmt.Println("CuEVM Debug: dynamic ABI method")
		// Generate fuzzed parameters for the function call
		args := make([]any, len(selectedMethod.Method.Inputs))
		g.generatedArrayLengths = make([]int, 0)
		for i := 0; i < len(args); i++ {
			// Create our fuzzed parameters.
			input := selectedMethod.Method.Inputs[i]
			// args[i] = valuegeneration.GenerateAbiValue(g.config.ValueGenerator, &input.Type)
			if len(g.generatedArrayLengths) == 0 {
				args[i] = valuegeneration.GenerateAbiValueWithArrayLength(g.config.ValueGenerator, &input.Type, -1)
			} else {
				// 50% chance to use the existing array length
				if g.worker.randomProvider.Intn(2) == 0 {
					args[i] = valuegeneration.GenerateAbiValueWithArrayLength(g.config.ValueGenerator, &input.Type, -1)
				} else {
					random_idx := g.worker.randomProvider.Intn(len(g.generatedArrayLengths))
					args[i] = valuegeneration.GenerateAbiValueWithArrayLength(g.config.ValueGenerator, &input.Type, g.generatedArrayLengths[random_idx])
				}
			}
			// fmt.Println("CuEVM Debug: args[i]", args[i])
			// fmt.Println("CuEVM Debug: input.Type", input.Type)
			if input.Type.T == abi.SliceTy {
				reflectValue := reflect.ValueOf(args[i])
				actualLength := reflectValue.Len() // This will give you the length
				g.generatedArrayLengths = append(g.generatedArrayLengths, actualLength)
				// fmt.Println("CuEVM Debug: generatedArrayLengths", g.generatedArrayLengths)
			}
		}

		// Create our message using the provided parameters.
		// We fill out some fields and populate the rest from our TestChain properties.
		// fmt.Println("CuEVM Debug: dynamic ABI method", selectedMethod.Method.Sig)
		// fmt.Println("CuEVM Debug: args", args)

		msg, masks = calls.NewCallMessageWithAbiValueDataAndMask(selectedSender, &selectedMethod.Address, 0, value, g.worker.fuzzer.config.Fuzzing.TransactionGasLimit, big_one, big_zero, big_zero, &calls.CallMessageDataAbiValues{
			Method:      &selectedMethod.Method,
			InputValues: args,
		})

	}

	if g.worker.fuzzer.config.Fuzzing.TestChainConfig.SkipAccountChecks {
		msg.SkipAccountChecks = true
	}

	// Determine our delay values for this element
	blockNumberDelay := uint64(0)
	blockTimestampDelay := uint64(0)
	if fetch_index == 0 {
		blockNumberDelay = g.config.ValueGenerator.GenerateInteger(false, 64).Uint64() % (g.worker.fuzzer.config.Fuzzing.MaxBlockNumberDelay + 1)       // uint64(0)
		blockTimestampDelay = g.config.ValueGenerator.GenerateInteger(false, 64).Uint64() % (g.worker.fuzzer.config.Fuzzing.MaxBlockTimestampDelay + 1) // uint64(0)

		if blockNumberDelay > blockTimestampDelay {
			if blockTimestampDelay == 0 {
				blockNumberDelay = 0
			} else {
				blockNumberDelay %= blockTimestampDelay
			}
		}
	}
	// if g.worker.fuzzer.config.Fuzzing.MaxBlockNumberDelay > 0 {
	// 	blockNumberDelay = g.config.ValueGenerator.GenerateInteger(false, 64).Uint64() % (g.worker.fuzzer.config.Fuzzing.MaxBlockNumberDelay + 1)
	// }
	// if g.worker.fuzzer.config.Fuzzing.MaxBlockTimestampDelay > 0 {
	// 	blockTimestampDelay = g.config.ValueGenerator.GenerateInteger(false, 64).Uint64() % (g.worker.fuzzer.config.Fuzzing.MaxBlockTimestampDelay + 1)
	// }

	// For each block we jump, we need a unique time stamp for chain semantics, so if our block number jump is too small,
	// while our timestamp jump is larger, we cap it.

	// Return our call sequence element and masks.
	return calls.NewCallSequenceElement(selectedMethod.Contract, msg, blockNumberDelay, blockTimestampDelay), masks, nil
}

// callSeqGenFuncCorpusHead is a CallSequenceGeneratorFunc which prepares a CallSequenceGenerator to generate a sequence
// whose head is based off of an existing corpus call sequence.
// Returns an error if one occurs.
func callSeqGenFuncCorpusHead(sequenceGenerator *CallSequenceGenerator, sequence calls.CallSequence) error {
	// fmt.Println("CuEVM Debug: callSeqGenFuncCorpusHead")
	// Obtain a call sequence from the corpus
	corpusSequence, err := sequenceGenerator.worker.fuzzer.corpus.RandomMutationTargetSequence()
	if err != nil {
		return fmt.Errorf("could not obtain corpus call sequence for head mutation: %v", err)
	}
	// fmt.Println("CuEVM Debug: corpusSequence", corpusSequence)
	// Determine the length of the slice to be copied in the head.
	maxLength := utils.Min(len(sequence), len(corpusSequence))
	copy(sequence, corpusSequence[:maxLength])
	// fmt.Println("CuEVM Debug: sequence after mutation", sequence)
	return nil
}

// callSeqGenFuncCorpusTail is a CallSequenceGeneratorFunc which prepares a CallSequenceGenerator to generate a sequence
// whose tail is based off of an existing corpus call sequence.
// Returns an error if one occurs.
func callSeqGenFuncCorpusTail(sequenceGenerator *CallSequenceGenerator, sequence calls.CallSequence) error {
	// fmt.Println("CuEVM Debug: callSeqGenFuncCorpusTail")
	// Obtain a call sequence from the corpus
	corpusSequence, err := sequenceGenerator.worker.fuzzer.corpus.RandomMutationTargetSequence()
	if err != nil {
		return fmt.Errorf("could not obtain corpus call sequence for tail mutation: %v", err)
	}
	// fmt.Println("CuEVM Debug: corpusSequence", corpusSequence)
	// Determine a random position to slice the call sequence.
	maxLength := utils.Min(len(sequence), len(corpusSequence))
	targetLength := sequenceGenerator.worker.randomProvider.Intn(maxLength) + 1
	copy(sequence[len(sequence)-targetLength:], corpusSequence[len(corpusSequence)-targetLength:])
	// fmt.Println("CuEVM Debug: sequence after mutation", sequence)
	sequenceGenerator.generateFromTail = true
	return nil
}

// callSeqGenFuncSpliceAtRandom is a CallSequenceGeneratorFunc which prepares a CallSequenceGenerator to generate a
// sequence which is based off of two corpus call sequence entries, from which a random length head and tail are
// respectively sliced and joined together.
// Returns an error if one occurs.
func callSeqGenFuncSpliceAtRandom(sequenceGenerator *CallSequenceGenerator, sequence calls.CallSequence) error {
	// fmt.Println("CuEVM Debug: callSeqGenFuncSpliceAtRandom")
	// Obtain two corpus call sequence entries
	headSequence, err := sequenceGenerator.worker.fuzzer.corpus.RandomMutationTargetSequence()
	if err != nil {
		return fmt.Errorf("could not obtain head corpus call sequence for splice-at-random corpus mutation: %v", err)
	}
	tailSequence, err := sequenceGenerator.worker.fuzzer.corpus.RandomMutationTargetSequence()
	if err != nil {
		return fmt.Errorf("could not obtain tail corpus call sequence for splice-at-random corpus mutation: %v", err)
	}

	// Determine a random position to slice off the head of the call sequence.
	maxLength := utils.Min(len(sequence), len(headSequence))
	headSequenceLength := sequenceGenerator.worker.randomProvider.Intn(maxLength) + 1

	// Copy the head of the first corpus sequence to our destination sequence.
	copy(sequence, headSequence[:headSequenceLength])
	// fmt.Println("CuEVM Debug: sequence after head copy", sequence)
	// Determine a random position to slice off the tail of the call sequence.
	maxLength = utils.Min(len(sequence)-headSequenceLength, len(tailSequence))
	tailSequenceLength := sequenceGenerator.worker.randomProvider.Intn(maxLength + 1)
	// Copy the tail of the second corpus sequence to our destination sequence (after the head sequence portion).
	copy(sequence[headSequenceLength:], tailSequence[len(tailSequence)-tailSequenceLength:])
	// fmt.Println("CuEVM Debug: sequence after tail copy", sequence)
	return nil
}

// callSeqGenFuncInterleaveAtRandom is a CallSequenceGeneratorFunc which prepares a CallSequenceGenerator to generate a
// sequence which is based off of two corpus call sequence entries, from which a random number of transactions are
// taken and interleaved (each element of one sequence will be followed by an element of the other).
// Returns an error if one occurs.
func callSeqGenFuncInterleaveAtRandom(sequenceGenerator *CallSequenceGenerator, sequence calls.CallSequence) error {
	// fmt.Println("CuEVM Debug: callSeqGenFuncInterleaveAtRandom")
	// Obtain two corpus call sequence entries
	firstSequence, err := sequenceGenerator.worker.fuzzer.corpus.RandomMutationTargetSequence()
	if err != nil {
		return fmt.Errorf("could not obtain first corpus call sequence for interleave-at-random corpus mutation: %v", err)
	}
	secondSequence, err := sequenceGenerator.worker.fuzzer.corpus.RandomMutationTargetSequence()
	if err != nil {
		return fmt.Errorf("could not obtain second corpus call sequence for interleave-at-random corpus mutation: %v", err)
	}

	// Determine how many transactions to take from the first sequence and slice it.
	maxLength := utils.Min(len(sequence), len(firstSequence))
	firstSequenceLength := sequenceGenerator.worker.randomProvider.Intn(maxLength) + 1
	firstSequence = firstSequence[:firstSequenceLength]

	// Determine how many transactions to take from the second sequence and slice it.
	maxLength = utils.Min(len(sequence)-firstSequenceLength, len(secondSequence))
	secondSequenceLength := sequenceGenerator.worker.randomProvider.Intn(maxLength + 1)
	secondSequence = secondSequence[:secondSequenceLength]
	// fmt.Println("CuEVM Debug: firstSequence", firstSequence)
	// fmt.Println("CuEVM Debug: secondSequence", secondSequence)
	// Now that we have both sequences, and we know they will not exceed our destination sequence length, interleave
	// them.
	destIndex := 0
	largestSequenceSize := utils.Max(firstSequenceLength, secondSequenceLength)
	for i := 0; i < largestSequenceSize; i++ {
		if i < len(firstSequence) {
			sequence[destIndex] = firstSequence[i]
			destIndex++
		}
		if i < len(secondSequence) {
			sequence[destIndex] = secondSequence[i]
			destIndex++
		}
	}
	// fmt.Println("CuEVM Debug: sequence after interleaving", sequence)
	return nil
}

// prefetchModifyCallFuncMutate is a PrefetchModifyCallFunc, called by a CallSequenceGenerator to apply mutations
// to a call sequence element, prior to it being fetched.
// Returns an error if one occurs.
func prefetchModifyCallFuncMutate(sequenceGenerator *CallSequenceGenerator, element *calls.CallSequenceElement) error {
	// If this element has no ABI value based call data, exit early.
	if element.Call == nil || element.Call.DataAbiValues == nil {
		return nil
	}

	// Loop for each input value and mutate it
	abiValuesMsgData := element.Call.DataAbiValues
	for i := 0; i < len(abiValuesMsgData.InputValues); i++ {
		mutatedInput, err := valuegeneration.MutateAbiValue(sequenceGenerator.config.ValueGenerator, sequenceGenerator.config.ValueMutator, &abiValuesMsgData.Method.Inputs[i].Type, abiValuesMsgData.InputValues[i])
		if err != nil {
			return fmt.Errorf("error when mutating call sequence input argument: %v", err)
		}
		abiValuesMsgData.InputValues[i] = mutatedInput
	}
	// Re-encode the message's calldata
	element.Call.WithDataAbiValues(abiValuesMsgData)

	return nil
}
